---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: teknton-buildah-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: tekton-buildah-pipeline
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/dmi-vlasenko-tekton-buildah
    - name: image-repo
      value: quay.io/dmiv/tekton-buildah
    - name: app-name
      value: tekton-buildah
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
